projectceladon/linux-intel-lts2022

drivers/gpu/drm/drm_fb_helper.c, drivers/gpu/drm/drm_ioctl.c, drivers/gpu/drm/i915/i915_pci.c, drivers/misc/mei/gsc-me.c, drivers/misc/mei/hdcp/mei_hdcp.c, drivers/misc/mei/pxp/mei_pxp.c
disable dg2 dg1 devices for pkt i915
hack driver name i915_ag to i915
mei_gsc support load the huc for dgpu
Tracked-On: OAM-118821
=> using i915_ag for dgpu device

drivers/spi/Kconfig, drivers/spi/Makefile, drivers/spi/spi-virtio.c, include/uapi/linux/virtio_ids.h, include/uapi/linux/virtio_spi.h
Test done:
Boot up Android as a guest of ACRN with one Virtio SPI device.
- Run ls -l /sys/class/spi_master/ to find the Virtio SPI controller and
underlying SPI devices
- Run spidev_test to transfer data with test loopback SPI device.
Tracked-On: OAM-122209
=> Virtio spi controller driver

drivers/net/wireless/intel/iwlwifi/mvm/Makefile, drivers/net/wireless/intel/iwlwifi/mvm/mvm.h, drivers/net/wireless/intel/iwlwifi/mvm/vendor-cmd.c
VtsHalWifiChipTargetTest is failing as the vendor
command requests are failing.
Vendor command file is compiled based on CONFIG_IWLMEI.
As CONFIG_IWLMEI is not enabled, vendor command is not
compiled at all.
Fix the issue by unconditionally compiling the vendor
command file.
Test:
VtsHalWifiChipTargetTest can pass
Tracked-On: OAM-122539
Change-Id: Ic345a75ef08ff07dd96164fe8d13011208b57a2a
=> [VTS FIX] Wifi: iwlmvm: enable vendor-cmd for vts test

drivers/gpu/drm/i915/gem/i915_gem_object.c
i915_gem_obj_insert_pid is currently defined under DRM_I915_MEMTRACK config but i915_gem_open_object is not under the config. When the i915 memtrack is disabled, build error is seen due to i915_gem_obj_insert_pid definition missing.
Fix the issue by having i915_gem_open_object under DRM_I915_MEMTRACK config.
Tests done:
- Build with i915 memtrack driver enabled
- Build with i915 memtrack driver disabled
- Android boot
Tracked-On: OAM-122631
=> Fix i915 build error when i915 memtrack is not enabled

drivers/tee/optee/core.c
Test Done:
adb reboot twice successfully.
power on, power off work normally.
adb, BT, Wi-Fi audio work normally.
Tracked-On: OAM-120375
=> Add PCI Subsystem ID to diff IVSheme device

drivers/virtio/virtio_shmem.c, include/linux/virtio_shm.h
This patch add a function to map the gpa to ivshmem offset.
Test done:
1. QNX + virtio camera + IPU Camera
2. QNX + virtio camera + UVC Camera
Tracked-On: OAM-124423
=> Mofify for ivshmem

drivers/gpu/drm/virtio/virtgpu_kms.c, drivers/gpu/drm/virtio/virtgpu_prime.c
if virtio gpu is working on top of ivshmem
then do not accept buffer allocated by i915 to
import, since it can not be displayed.
Tracked-On: OAM-124035
=> virtio gpu: add import dmabuf check

include/uapi/linux/virtio_gpu.h
Original value 31 is reserved for extensions to the queue and feature negotiation mechanisms by virtio spec (Chapter 2, Section 2.2). To avoid violation to the spec, change the value to 13, which is within the range for specific virtio device type.
Test-done:
- Boot AAOS with dGPU SR-IOV VF and virtio-GPU backed by dGPU display.
Tracked-On: OAM-124694
=> drm/virtio: Change value of feature ALLOW_P2P to 13

drivers/gpu/drm/i915/i915_pci.c, kernel/module/main.c
=> dkms: optimize the dg2 kernel driver loading time

drivers/virtio/virtio_shmem.c
For virtio-input devices, writing to config area is defined as selecting config pages. But in virtio over shmem implement, this operation is not supported. The W/A is to update config area upon config selection in BE, and delay a short while after cfg write in FE. This delay does not reduce performance as it only happens during init stage.
Test done:
Using keyboard/mouse/touchscreen over virtio-input on QNX
Tracked-On: OAM-124493
=> QNX: W/A for virtio-input over shmem

drivers/gpu/drm/virtio/virtgpu_drv.h, drivers/gpu/drm/virtio/virtgpu_kms.c
vblank array in virtio gpu struct is zero array, and driver does not allocate buffer for it, so set max vblank number and check it.
Tracked-On: OAM-126006
=> drm/virtio: set max vblank number

drivers/gpu/drm/virtio/virtgpu_drv.h, drivers/gpu/drm/virtio/virtgpu_plane.c, drivers/gpu/drm/virtio/virtgpu_vq.c, include/uapi/linux/virtio_gpu.h
put set modifier ahead of set scanout to avoid set scaout operation can not get the lastest modifier, and refine set modifer api to pass resource id to backend.
Tests Done:
1, virito-gpu + iGPU
Tracked-On: OAM-123901
=> drm/virtio: put set modifier ahead of set scanout

drivers/gpu/drm/i915/i915_pci.c, kernel/module/main.c
nuclear_pageflip=1 enable_guc=0x7 max_vfs=7 modeset=1 fastboot=1
=> dkms: add module load parameters

drivers/gpu/drm/i915/i915_gpu_error.h, drivers/gpu/drm/i915/i915_sysfs.c
Fix the panic issue:
[   28.635141] BUG: unable to handle page fault for address: 0000000110874038
[   28.637556] #PF: supervisor read access in kernel mode
[   28.638812] #PF: error_code(0x0000) - not-present page
[   28.639678] PGD 0 P4D 0
[   28.640076] Oops: 0000 [#1] PREEMPT SMP NOPTI
[   28.641086] CPU: 0 PID: 1220 Comm: HwBinder:535_4 Tainted: G S   U  W  O       6.1.105-android14-0-g30187d714e80-dirty #8
[   28.643061] RIP: 0010:strlen+0x10/0x30
[   28.643603] Code: cc cc cc cc cc 00 00 cc cc 00 90 90 90 90 90 90 90 90 90 90 90 b8 6f 23 7e aa 55 48 89 e5 48 c7 c0 ff ff ff ff 0f 1f 44 00 00 <80> 7c 07 01 00 48 8d 40 01 75 f5 5d c3 cc cc cc cc cc 00 00 cc cc
[   28.646457] RSP: 0018:ffffbe58c4ad3cd8 EFLAGS: 00010202
[   28.647788] RAX: ffffffffffffffff RBX: 0000000110874038 RCX: …
=> I915: optimize create/remove syfs entry for memtrack interface

drivers/bluetooth/Kconfig
Disable Broadcom and Realtech Bluetooth config,
to reduce Bluetooth driver init time.
Tests:
Bluetooth can boot up success and init time less
Tracked-On: OAM-127329
=> Disable Broadcom and Realtech Bluetooth config

drivers/gpu/drm/virtio/virtgpu_debugfs.c, drivers/gpu/drm/virtio/virtgpu_drv.h, drivers/gpu/drm/virtio/virtgpu_object.c, drivers/gpu/drm/virtio/virtgpu_prime.c
For PRIME objects we need to cache the addresses and use them to re-create resources upon resuming.
=> drm/virtio: Save address entries of PRIME objects

drivers/acpi/sleep.c, drivers/gpu/drm/drm_atomic_helper.c, include/drm/drm_atomic.h, include/linux/suspend.h
Add the first atomic commit log after resume
Tracked-On:
=> DRM: Add atomic commit log for resume

drivers/gpu/drm/virtio/virtgpu_debugfs.c, drivers/gpu/drm/virtio/virtgpu_drv.h, drivers/gpu/drm/virtio/virtgpu_object.c, drivers/gpu/drm/virtio/virtgpu_prime.c
Backport patches in PR https://github.com/projectceladon/linux-intel-lts2022/pull/78 to stable branch.
=> Stable fix prime

drivers/acpi/sleep.c, drivers/gpu/drm/drm_atomic_helper.c, include/drm/drm_atomic.h, include/linux/suspend.h
Print the period from S3 resume to firstly display commit
Tracked-On: OAM-128887
=> DRM: Add the first atomic commit time for resume

drivers/gpu/drm/virtio/virtgpu_drv.h, drivers/gpu/drm/virtio/virtgpu_ioctl.c, drivers/gpu/drm/virtio/virtgpu_kms.c, drivers/gpu/drm/virtio/virtgpu_prime.c, drivers/gpu/drm/virtio/virtgpu_vq.c, include/uapi/drm/virtgpu_drm.h, include/uapi/linux/virtio_gpu.h
get config bitmask for crtc VF LMEM config and expose to user space by get param ioctl, compare the dma buf name for p2p specificly and notify backend.
Tracked-On: OAM-129106
Signed-off-by: hangliu1 <hang1.liu@intel.com>
=> add support for VF LMEM type BLOB creation

drivers/media/platform/virtio/virtio-camera.c
This patch adds the Userptr interface and sets identifiers for each video node.
Test done:
1 launch AAOS
2 adb connect and adb root
3 adb shell
4 cat /sys/class/video4linux/*/name
Output:
vCamera_0
vCamera_1
vCamera_2
vCamera_3
Tracked-On: OAM-129442
=> Refine virtio camera inferface

drivers/gpu/drm/virtio/virtgpu_display.c, drivers/gpu/drm/virtio/virtgpu_vq.c
...to avoid potential race condition of event handling.
=> drm/virtio: Protect cached vblank events with drm_event_lock

drivers/media/platform/virtio/virtio-camera.c, drivers/media/v4l2-core/v4l2-dev.c, drivers/media/v4l2-core/v4l2-ioctl.c, include/media/v4l2-dev.h
Issue-Detailed: UVC camera messes up video device node sequence. So it's necessary to rearrange different types of camera device to their own device node names:
virtiocamera: /dev/virtvideo*
uvc camera: /dev/video*
Issue-Fixed: Define new v4l2 device type as VFL_TYPE_VIRTCAM whose name_base is 'virtvideo' and set virtiocamera device type as VIRTCAM.
Tested-On: /dev/virtvideo* created for virtiocamera devices. Those video camera devices can preview/capture/record.
Tracked-On: OAM-129620
=> Change virtiocamera device node name.

init/main.c
Print tsc when starting kernel and init process to help measure android cold boot accurately.
Tracked-On: OAM-130207
=> init/main.c: Print tsc when starting kernel and init process

arch/x86/include/asm/mwait.h
Monitor-less mwait is an extended x86 instruction feature that enables mwait be called without MONITOR pairing.
With the monitor-less mwait implementation, monitor is no longer required before calling mwait. And kernel wakes up from Cx idle state by interrupts, instead of mem write on the monitored address (which is hard for hypervisor to emulate).
The implementation includes:
1. Hypervisor will emulate CPUID.05H.ECX[2] to indicate the presence of monitor-less mwait.
2. Kernel marks ecx bit2 for MWAIT instruction to indicate it is calling a monitor-less mwait.
3. Kernel clears TIF_POLLING_NRFLAG before monitor-less mwait so that the idle core is going to be waked up by interrupts.
=> ACRN: implementation of monitor-less mwait

drivers/dma-buf/dma-buf.c, drivers/gpu/drm/virtio/virtgpu_object.c, drivers/gpu/drm/virtio/virtgpu_plane.c, drivers/gpu/drm/virtio/virtgpu_prime.c, include/linux/dma-buf.h
Use atomic check hook to ensure the framebuffers we are going to set satisfy the requirement for dGPU.
=> drm/virtio: Ensure lmem objects are used for dGPU backing CRTC
